package com.seanhoapps.chessgame;

public enum GameEvent {
	MOVE_COMPLETED, KING_CHECKED,
	AWAITING_NEXT_MOVE, AWAITING_PROMOTION_RESPONSE,
	GAME_OVER_CHECKMATED, GAME_OVER_STALEMATED, NEW_GAME_STARTED;
}